import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';

const homeGridData = [
  {
    id: 1,
    img: '/image/home/home-grid-1.jpg',
    text: 'Merging retail, food, art, and culture, Canal Street Market highlights top retail and design concepts, restaurants, and up-and-coming players in the downtown New York City community.',
  },
  {
    id: 2,
    img: '/image/home/home-grid-2.jpg',
    text: 'Retail Market Hours: Fri– Sun: 11:00AM - 7:00PM',
  },
  {
    id: 3,
    img: '/image/home/home-grid-3.jpg',
    text: 'Food Hall Hours: Mon – Thurs: 11:00AM - 6:00PM Fri– Sun: 11:00AM - 7:00PM',
  },
];

const homeRowData = [
  {
    id: 1,
    date: '10/22',
    text: 'Small Business Retail Pop Up Weekend!',
  },
  {
    id: 2,
    date: '02/07',
    text: 'New Balance x Paperboy Paris by Greenhouse @ Canal Street Market',
  },
  {
    id: 3,
    date: '12/11',
    text: 'Hack City 12/11',
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main>
        <div className='home'>
          {/* hero */}
          <section className='home__hero'>
            <h1 className='home__hero__title'>
              Canal Street Market is a carefully curated retail market, food
              hall & community space open year-round at 265 Canal Street.
              Support Small Business this weekend!
            </h1>
          </section>
          {/* media */}
          <section className='home__media'>
            <div className='home__media__img'>
              <Image
                src='/image/home/home-hero.jpg'
                layout='fill'
                alt='home-hero'
                objectFit='cover'
              />
            </div>
          </section>
          {/* columns */}
          <section className='home__columns'>
            <h2 className='home__columns__title'>A New Kind of Market</h2>
            <div className='home__columns__grid'>
              {homeGridData.map((item) => (
                <div key={item.id} className='home__grid__container'>
                  <div className='home__grid__media'>
                    <Image
                      src={item.img}
                      layout='fill'
                      objectFit='cover'
                      alt={`grid-${item.id}`}
                    />
                  </div>
                  <p className='home__grid__text'>{item.text}</p>
                </div>
              ))}
            </div>
          </section>
          {/* events */}
          <section className='home__events'>
            <div className='home__events__header'>
              <h2 className='home__header__logo'>活動</h2>
              <h1 className='home__header__title'>Marker Events</h1>
              <h2 className='home__header__logo'>活動</h2>
            </div>
            <div className='home__events__row'>
              {homeRowData.map((item) => (
                <div className='home__row__container' key={item.id}>
                  <span className='home__row__date'>{item.date}</span>
                  <p className='home__row__text'>{item.text}</p>
                </div>
              ))}
              <button className='home__events__button'>see all</button>
            </div>
          </section>
          {/* address */}
          <section className='home__address'>
            <div className='home__address__container'>
              <h3 className='home__address__text'>
                265 Canal St. New York, NY
              </h3>
            </div>
            <div className='home__address__container'>
              <div className='home__address__media'>
                <Image
                  src='/image/home/home-address.jpg'
                  layout='fill'
                  objectFit='cover'
                  alt='address'
                />
              </div>
            </div>
          </section>
        </div>
        <Footer />
      </main>
    </div>
  );
}

const footerData = [
  { id: 1, text: 'Email us' },
  { id: 2, text: 'Follow us on facebook' },
  { id: 3, text: 'Follow us on instagram' },
];

const Footer = () => {
  return (
    <footer className='footer'>
      <div className='footer__interested'>
        <h3 className='footer__interested__title'>
          Interested in becoming a vendor?
        </h3>
        <button className='footer__interested__button'>click here</button>
      </div>
      <div className='footer__socials'>
        {footerData.map((item) => (
          <div className='footer__socials__container' key={item.id}>
            <div className='footer__socials__icon'></div>
            <p className='footer__socials__text'>{item.text}</p>
          </div>
        ))}
      </div>
      <div className='footer__contact'>
        <p className='footer__contact__title'>
          Stay up to date with our newsletter
        </p>
        <form className='footer__contact__form'>
          <input
            type='email'
            placeholder='Email'
            className='footer__contact__input'
          />
          <input type='submit' className='footer__contact__icon'></input>
        </form>
      </div>
      <div className='footer__legal'>
        <p className='footer__legal__copyright'>
          Copyright Canal Street Market 2019
        </p>
        <p className='footer__legal__privacy'>Privacy Policy</p>
        <p className='footer__legal__login'>Vendor Login</p>
        <p className='footer__legal__creator'>Site by Zero</p>
      </div>
    </footer>
  );
};

const navData = [
  {
    id: 1,
    page: 'home',
    title: 'Home',
  },
  {
    id: 2,
    page: 'food',
    title: 'Food',
  },
  {
    id: 3,
    page: 'retail',
    title: 'Retail',
  },
  {
    id: 4,
    page: 'community',
    title: 'Community',
  },
];

const Navbar = () => {
  const [mainPage, setMainPage] = useState('home');
  return (
    <nav>
      {navData.map((item) => (
        <div
          key={item.id}
          className={
            item.page === mainPage
              ? `nav__link nav__link__open nav__link__${item.page}`
              : 'nav__link'
          }
          style={{}}
          onClick={() => setMainPage(item.page)}
        >
          <p className='nav__link__text'>{item.title}</p>
        </div>
      ))}
    </nav>
  );
};
